name: Tofu Plan 

on: 
    pull_request: 
        branches: ["main"] 
        paths: ["td5/scripts/tofu/live/lambda-sample/**"] 

jobs: 
    plan: 
        name: "Tofu Plan" 
        runs-on: ubuntu-latest 
        permissions: 
            pull-requests: write 
            id-token: write 
            contents: read 

        steps: 
            - name: Checkout repository
              uses: actions/checkout@v2 

            - name: Configure AWS credentials 
              uses: aws-actions/configure-aws-credentials@v3 
              with:
                  role-to-assume: ${{ secrets.PLAN_ROLE_ARN }}
                  role-session-name: plan-${{ github.run_number }}-${{ github.actor }} 
                  aws-region: us-east-2 

            - name: Setup OpenTofu
              uses: opentofu/setup-opentofu@v1 

            - name: Run tofu plan 
              id: plan 
              working-directory: td5/scripts/tofu/live/lambda-sample 
              run: | 
                  tofu init -no-color -input=false 
                  tofu plan -no-color -input=false -lock=false 

            - name: Post plan output in PR comment
              uses: peter-evans/create-or-update-comment@v4 
              if: always() 
              env: 
                  RESULT_EMOJI: ${{ steps.plan.outcome == 'success' && '✅' || '⚠ ' }} 
              with:
                  issue-number: ${{ github.event.pull_request.number }} 
                  body: | 
                      ## ${{ env.RESULT_EMOJI }} `tofu plan` output 
                      ```${{ steps.plan.outputs.stdout }}```
